---

- include: cgroups-v2.yml
  when: ansible_kernel.split('.') >= '5.2'.split('.') and not ansible_virtualization_type | regex_search("docker|container")

- include: pre-install.yml

- include: repo-{{ ansible_os_family | lower }}.yml

- include: podman-fuse-overlayfs.yml
  when: ansible_distribution_release is regex('bionic')

- include: podman-slirp4netns.yml
  when: ansible_distribution_release is regex('bionic')

- include: crun.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version | int <= 7

- include: install.yml

- include: podman-rootless.yml
  when: podman_rootless_mode | bool

- include: podman-compose.yml
  when: podman_compose_install | bool

- include: img.yml
  when: podman_img_install | bool
