---

- name: Cgroups v2 configuration steps
  include_tasks: cgroups-v2.yml
  when: >
    (ansible_kernel.split('.')[0:2] | join('.')) is version('5.2', operator='gt', strict=True)
    and not ansible_virtualization_type | regex_search("docker|container")

- name: Pre-installation steps
  include_tasks: pre-install.yml

- name: Repository configuation steps
  include_tasks: repo-{{ ansible_os_family | lower }}.yml

- name: Fuse-overlayfs configuration steps
  include_tasks: podman-fuse-overlayfs.yml
  when: ansible_distribution_release is regex('bionic')

- name: Slirp4netns configuration steps
  include_tasks: podman-slirp4netns.yml
  when: ansible_distribution_release is regex('bionic')

- name: Crun installation steps
  include_tasks: crun.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version | int <= 7

- name: Main installation steps
  include_tasks: install.yml

- name: Rootless mode configuration steps
  include_tasks: podman-rootless.yml
  when: podman_rootless_mode | bool

- name: Install podman-compose steps
  include_tasks: podman-compose.yml
  when: podman_compose_install | bool

- name: Install img builder steps
  include_tasks: img.yml
  when: podman_img_install | bool
