---
# https://github.com/containers/podman/blob/master/docs/tutorials/rootless_tutorial.md

- name: Set default OCI runtime - crun
  lineinfile:
    path: "/usr/share/containers/containers.conf"
    regexp: '(^#\ runtime\ =.*"crun"$)'
    line: 'runtime = "crun"'

- name: Set storage driver to overlay
  lineinfile:
    path: "/etc/containers/storage.conf"
    regexp: '^driver\ =\ \"\w+\"$'
    line: 'driver = "overlay"'

- name: Set fuse-overlayfs executable
  lineinfile:
    path: "/etc/containers/storage.conf"
    regexp: '#mount_program'
    line: 'mount_program = "/usr/bin/fuse-overlayfs"'

- name: Set user rootless storage path
  lineinfile:
    path: "/etc/containers/storage.conf"
    regexp: '(^#\ rootless_storage_path.*)'
    line: 'rootless_storage_path = "$HOME/.local/share/containers/storage"'

- name: Enumerate max gid
  set_fact:
    max_user_gid: "{{ lookup('pipe','cut -f 3 -d: /etc/passwd | sort -n | tail -n 1') }}"

- name: Enable kernel tweaks
  template:
    src: "sysctl.d/00-rootless.conf.j2"
    dest: "/etc/sysctl.d/00-rootless.conf"
    mode: 0600
  notify:
    - Reload sysctl

- name: Flush handlers
  meta: flush_handlers

- name: Update /etc/subuid
  lineinfile:
    path: "/etc/subuid"
    regexp: '^{{ ansible_user_id }}'
    line: "{{ ansible_user_id }}:{{ lookup(\"pipe\", \"id -u \" + ansible_user_id) }}:65536"
  become: yes
  when: not ansible_user_id == 'root'

- name: Update /etc/subgid
  lineinfile:
    path: "/etc/subgid"
    regexp: '^{{ ansible_user_id }}'
    line: "{{ ansible_user_id }}:{{ lookup(\"pipe\", \"id -g \" + ansible_user_id) }}:65536"
  become: yes
  when: not ansible_user_id == 'root'
