---

- name: Check podman-compose exists
  stat:
    path: "{{ item.dest }}"
  register: current_podman_compose
  with_items:
    - "{{ podman_compose_info }}"

- name: Delete podman-compose if exists
  file:
    path: "{{ item.item.dest }}"
    state: absent
  with_items:
    - "{{ current_podman_compose.results }}"
  when: item.stat.exists | bool
  changed_when: false

- name: Install podman compose
  get_url:
    url: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - "{{ podman_compose_info }}"
  changed_when: false
