---

- name: populate debian packages
  set_fact:
    system_package_list: "{{ _system_package_list['default'] + _system_package_list[ansible_distribution] }}"
  when: ansible_os_family == 'Debian'

- name: populate redhat packages
  set_fact:
    system_package_list: |
          {% if ansible_distribution == 'Fedora' %}
          {{ _system_package_list['default'] + _system_package_list[ansible_distribution] }}
          {% else %}
          {{ _system_package_list['default'] + _system_package_list[ansible_distribution] + _redhat_specific_packages[ansible_distribution_major_version] }}
          {% endif %}
  when: ansible_os_family == 'RedHat'

- name: skip slirp4netns/libfuse3-dev packages for ubuntu bionic
  set_fact:
    system_package_list: "{{ system_package_list | difference('slirp4netns,libfuse3-dev') }}"
  when: ansible_distribution_release is regex('bionic')

- name: Install system packages
  action: >
    {{ ansible_pkg_mgr }} name={{ system_package_list }} state=present update_cache=yes
  become: yes
  when: system_package_list is defined
