---

- name: redhat - disable container-tools modules
  shell: |
    set -o pipefail
    dnf module disable container-tools -qy
  args:
      executable: /bin/bash
  become: true
  changed_when: false
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version| int >= 8

#- name: Install system packages
#  action: >
#    {{ ansible_pkg_mgr }} name={{ system_package_list }} state=present update_cache=yes
#    vars:
#      packages: "{{ system_package_list }}"
#  become: yes
#  when: system_package_list is defined

- name: Enable lsm5/container-selinux
  community.general.copr:
    state: enabled
    name: "lsm5/container-selinux"
  when: ansible_distribution == 'Amazon'

- name: Enable rhcontainerbot/container-selinux
  community.general.copr:
    state: enabled
    name: "rhcontainerbot/container-selinux"
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version| int >= 8

- name: add repo configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0600
  with_items:
    - "{{ repo_template_file }}"
