---

- name: Enable buster-backports for libseccomp2
  lineinfile:
    path: "/etc/apt/sources.list"
    regexp: '.+buster-backports.+'
    line: "deb http://deb.debian.org/debian buster-backports main"
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version|int == 10

- name: Add repo configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0600
  with_items:
    - "{{ repo_template_file }}"

- name: Install podman repo release key
  apt_key:
    url: "{{ release_key_url }}"
    state: present

# libseccomp2 fix - https://github.com/containers/podman/issues/7508#issuecomment-746245356
- name: Update APT cache
  apt:
    update_cache: yes
  changed_when: false

- name: Install newer version of libseccomp2
  apt:
    name: "libseccomp-dev"
    state: present
    update_cache: yes
    default_release: "buster-backports"
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version|int == 10
