---

- name: redhat - disable container-tools modules
  shell: |
    set -o pipefail
    dnf module disable container-tools -qy
  args:
      executable: /bin/bash
  become: true
  changed_when: false
  when: (ansible_distribution is regex('CentOS') and ansible_distribution_major_version| int >= 8)

- name: Enable lsm5/container-selinux
  community.general.copr:
    state: enabled
    name: "lsm5/container-selinux"
  when: ansible_distribution == 'Amazon'

- name: Enable rhcontainerbot/container-selinux
  community.general.copr:
    state: enabled
    name: "rhcontainerbot/container-selinux"
  when: (ansible_distribution is regex('CentOS') and ansible_distribution_major_version| int >= 8)

- name: add repo configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0600
  with_items:
    - "{{ repo_template_file }}"
  when: not ansible_distribution == 'Fedora'
