---

- name: restart dbus for user
  systemd:
    state: restarted
    name: dbus
    scope: user
  when: ansible_distribution == 'Debian' and (not ansible_virtualization_type | regex_search("docker|container"))

- name: Reload sysctl
  shell: |
    set -o pipefail
    sysctl -p /etc/sysctl.d/00-podman.conf
  args:
      executable: /bin/bash
  become: true
  changed_when: false
  ignore_errors: yes
